version: "3"

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'dota'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'Dotabp_2019'
       MYSQL_ROOT_PASSWORD: 'Dotabp_2019'

  app:
    restart: always
    build: . # Current directory!
    command: "python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      